project_id = "pbfgqbtppeztnlotqnrz"

[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = true

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.get-paddle-price]
verify_jwt = false

[functions.subscription-lifecycle]
verify_jwt = true
